### ISSUE TITLE
Tidy for xml

### ISSUE THREAD

**Issue by DZ84** [dense-analysis/ale#3404]
**Name: Tidy

Tidy is already offered for html, but it also has xml functionality.

**Comment by rafaelrojasmiliani** [comment]
This will great also for the ROS community working with roslaunch, and other xml-based files.

**Comment by rafaelrojasmiliani** [comment]
I got how to use tidy!! You only need a .tidyrc in your repo. In attachment an example. A complete list of the available tags is [here](https://api.html-tidy.org/tidy/quickref_next.html#PrettyPrintHeader).
```yaml
input-xml: yes
quiet: yes
indent: yes
indent-attributes: yes
indent-spaces: 4
char-encoding: utf8
wrap: 0
wrap-asp: no
wrap-jste: no
wrap-php: no
wrap-sections: no
```
